title: Tan Tran Cong # your name (or website title) here
logo: "/images/portrait_2_invert.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI/ML Engineer
  <br><br>
  Ho Chi Minh city, Vietnam
  <br><br>
  <a href="https://github.com/tranctan">View My Github</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/tan-tran-cong/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-187461250-1 # your Google Analytics tracking ID here
